// ============================================================
// Python Code Generator — compiles Lens IR to Python
// ============================================================

import {
  IRDocument, IRSchema, IRSchemaField, IRAnnotation,
  IRTypeAlias, IRMapping, IRMappingField, IRExpr,
  IRFieldAccess, IRLiteral, IRFunctionCall, IRMatch,
  IRMatchArm, IRPipe, IRBinary, IRCoalesce, IRSubMapping,
  IRArrayLiteral, IResolvedType,
} from '../ir';

export interface PythonGenOptions {
  /** Generate runtime functions inline (default true) */
  includeRuntime?: boolean;
}

export function generatePython(
  ir: IRDocument,
  options: PythonGenOptions = {},
): string {
  const opts = { includeRuntime: true, ...options };
  const lines: string[] = [];
  const indent = (s: string, level: number = 1) =>
    '    '.repeat(level) + s;

  // Header
  lines.push('# ============================================================');
  lines.push('# Generated by Lens DSL compiler — DO NOT EDIT');
  lines.push('# ============================================================');
  lines.push('');
  lines.push('from __future__ import annotations');
  lines.push('from dataclasses import dataclass, field');
  lines.push('from datetime import datetime, timezone');
  lines.push('from decimal import Decimal');
  lines.push('from typing import Literal, Optional, Union, Any');
  lines.push('from uuid import UUID');
  lines.push('import re');
  lines.push('');

  // ---- Runtime ----
  if (opts.includeRuntime) {
    lines.push(...generatePythonRuntime());
  }

  // ---- Type Aliases ----
  if (ir.typeAliases.length > 0) {
    lines.push('# ---- Type Aliases ----');
    for (const ta of ir.typeAliases) {
      lines.push(...generateTypeAlias(ta));
      lines.push('');
    }
  }

  // ---- Data Classes (Schemas) ----
  lines.push('# ---- Data Classes ----');
  // Topological sort: schemas without dependencies first
  const sorted = topologicalSort(ir.schemas);
  for (const schema of sorted) {
    lines.push(...generateDataclass(schema));
    lines.push('');
  }

  // ---- Mapping Functions ----
  if (ir.mappings.length > 0) {
    lines.push('# ---- Mapping Functions ----');
    for (const mapping of ir.mappings) {
      lines.push(...generateMappingFunction(mapping));
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ============================================================
// Runtime
// ============================================================
function generatePythonRuntime(): string[] {
  return [
    '# ---- Runtime Functions ----',
    '',
    'def __trim(s: str) -> str:',
    '    return s.strip()',
    '',
    'def __title_case(s: str) -> str:',
    '    return s.strip().title()',
    '',
    'def __lowercase(s: str) -> str:',
    '    return s.lower()',
    '',
    'def __uppercase(s: str) -> str:',
    '    return s.upper()',
    '',
    'def __normalize_email(s: str) -> str:',
    '    return s.strip().lower()',
    '',
    'def __normalize_city(s: str) -> str:',
    '    return s.strip().title()',
    '',
    'def __parse_uuid(s: str) -> str:',
    '    s = s.strip()',
    '    uuid_re = re.compile(r\'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$\', re.IGNORECASE)',
    '    if not uuid_re.match(s):',
    '        raise ValueError(f"Invalid UUID format: {s!r}")',
    '    return s',
    '',
    'def __parse_int(s: str) -> int:',
    '    try:',
    '        return int(s)',
    '    except ValueError:',
    '        raise ValueError(f"Cannot parse integer from: {s!r}")',
    '',
    'def __to_string(val: Any) -> str:',
    '    return str(val)',
    '',
    'def __filter_none(arr: list) -> list:',
    '    return [x for x in arr if x is not None]',
    '',
    'def __split_first(s: str) -> str:',
    '    return s.split(\' \', 1)[0]',
    '',
    'def __split_last(s: str) -> str:',
    '    return s.rsplit(\' \', 1)[-1]',
    '',
    'def __now() -> datetime:',
    '    return datetime.now(timezone.utc)',
    '',
  ];
}

// ============================================================
// Type Alias
// ============================================================
function generateTypeAlias(ta: IRTypeAlias): string[] {
  const name = ta.name;
  if (ta.defKind === 'regex') {
    return [`# ${name}: refined type matching /${ta.pattern}/`, `${name} = str`];
  }
  if (ta.defKind === 'union') {
    const literals = (ta.variants ?? []).map((v: string) => JSON.stringify(v)).join(', ');
    return [`${name} = Literal[${literals}]`];
  }
  // wrapper
  const pyType = irTypeToPython(ta.resolvedType);
  return [`${name} = ${pyType}`];
}

// ============================================================
// Schema → Dataclass
// ============================================================
function generateDataclass(schema: IRSchema): string[] {
  const lines: string[] = [];
  lines.push(`@dataclass`);
  lines.push(`class ${schema.name}:`);

  const requiredFields: IRSchemaField[] = [];
  const optionalFields: IRSchemaField[] = [];

  for (const f of schema.fields) {
    if (hasAnnotation(f, 'auto') || hasAnnotation(f, 'audit') || f.type.kind === 'optional') {
      optionalFields.push(f);
    } else {
      requiredFields.push(f);
    }
  }

  // Required fields first (dataclass ordering)
  for (const f of [...requiredFields, ...optionalFields]) {
    const anns = f.annotations.map(formatAnnotation).filter(Boolean);
    if (anns.length > 0) {
      lines.push(`    # ${anns.join(', ')}`);
    }
    const pyType = irTypeToPython(f.type);
    if (optionalFields.includes(f)) {
      lines.push(`    ${f.name}: ${pyType} = None`);
    } else {
      lines.push(`    ${f.name}: ${pyType}`);
    }
  }

  return lines;
}

// ============================================================
// Mapping Function
// ============================================================
function generateMappingFunction(mapping: IRMapping): string[] {
  const lines: string[] = [];

  if (mapping.isBidirectional) {
    lines.push(`# Bidirectional Mapping: ${mapping.name} (${mapping.source} <-> ${mapping.target})`);

    // Forward
    lines.push(`def ${mapping.name}_forward(source: '${mapping.source}') -> '${mapping.target}':`);
    lines.push(`    return ${mapping.target}(`);
    for (const f of mapping.fields) {
      const val = exprToPython(f.expression, 'source');
      lines.push(`        ${f.name}=${val},`);
    }
    lines.push(`    )`);
    lines.push('');

    // Backward
    lines.push(`def ${mapping.name}_backward(source: '${mapping.target}') -> '${mapping.source}':`);
    lines.push(`    return ${mapping.source}(`);
    for (const f of (mapping.backwardFields ?? [])) {
      const val = exprToPython(f.expression, 'source');
      lines.push(`        ${f.name}=${val},`);
    }
    lines.push(`    )`);
  } else {
    lines.push(`# Mapping: ${mapping.name} (${mapping.source} -> ${mapping.target})`);
    lines.push(`def ${mapping.name}(source: '${mapping.source}') -> '${mapping.target}':`);
    lines.push(`    return ${mapping.target}(`);
    for (const f of mapping.fields) {
      const val = exprToPython(f.expression, 'source');
      lines.push(`        ${f.name}=${val},`);
    }
    lines.push(`    )`);
  }

  return lines;
}

// ============================================================
// Expression → Python
// ============================================================
function exprToPython(expr: IRExpr, sourceVar: string): string {
  switch (expr.kind) {
    case 'field_access': return fieldAccessToPython(expr, sourceVar);
    case 'literal': return literalToPython(expr);
    case 'function_call': return functionCallToPython(expr, sourceVar);
    case 'match': return matchToPython(expr, sourceVar);
    case 'pipe': return pipeToPython(expr, sourceVar);
    case 'binary': return binaryToPython(expr, sourceVar);
    case 'coalesce': return coalesceToPython(expr, sourceVar);
    case 'sub_mapping': return subMappingToPython(expr, sourceVar);
    case 'array_literal': return arrayLiteralToPython(expr, sourceVar);
    default: return 'None'; // unreachable, all IRExpr kinds covered
  }
}

function fieldAccessToPython(expr: IRFieldAccess, sourceVar: string): string {
  const path = expr.path;

  // Path starting with 'source' means accessing source fields
  if (path.length > 0 && path[0] === 'source') {
    const fieldPath = path.slice(1);
    if (fieldPath.length === 0) return sourceVar;
    return `${sourceVar}.${fieldPath.join('.')}`;
  }

  // Bare identifier — likely a union variant literal
  // In Python, union variants are just string identifiers
  return JSON.stringify(path[0]);
}

function literalToPython(expr: IRLiteral): string {
  if (typeof expr.value === 'string') return JSON.stringify(expr.value);
  if (expr.value === null) return 'None';
  if (typeof expr.value === 'boolean') return expr.value ? 'True' : 'False';
  return String(expr.value);
}

function functionCallToPython(expr: IRFunctionCall, sourceVar: string): string {
  const fnName = BUILTIN_FN_MAP[expr.name] ?? expr.name;
  const args = expr.args.map((a: IRExpr) => exprToPython(a, sourceVar));
  return `${fnName}(${args.join(', ')})`;
}

function matchToPython(expr: IRMatch, sourceVar: string): string {
  const subject = exprToPython(expr.subject, sourceVar);
  const lines: string[] = [];

  // For match with literal arms → dict lookup (idiomatic Python for enum mapping)
  const allArmsLiteral = expr.arms.every((a: IRMatchArm) => a.patterns.length > 0);
  if (allArmsLiteral && expr.arms.length > 0) {
    // Generate a dictionary lookup with .get() for default
    const entries: string[] = [];
    for (const arm of expr.arms) {
      const body = exprToPython(arm.body, sourceVar);
      for (const pat of arm.patterns) {
        entries.push(`        ${JSON.stringify(pat)}: ${body}`);
      }
    }
    const defaultBody = expr.defaultArm
      ? exprToPython(expr.defaultArm, sourceVar)
      : 'None';

    lines.push(`({  # match expression`);
    lines.push(...entries.map(e => e + ','));
    lines.push(`    }.get(${subject}, ${defaultBody}))`);
    return lines.join('\n');
  }

  // Fallback: if/elif chain
  lines.push(`_match_val = ${subject}`);
  const lastIdx = expr.arms.length - 1;
  for (let i = 0; i < expr.arms.length; i++) {
    const arm = expr.arms[i];
    const prefix = i === 0 ? 'if' : 'elif';
    if (arm.patterns.length === 0) {
      // wildcard — should be 'else' but treated as always true
      lines.push(`    ${prefix} True:`);
    } else {
      const conditions = arm.patterns
        .map((p: string | number | boolean) => `_match_val == ${JSON.stringify(p)}`)
        .join(' or ');
      lines.push(`    ${prefix} ${conditions}:`);
    }
    lines.push(`        _match_result = ${exprToPython(arm.body, sourceVar)}`);
  }
  if (expr.defaultArm) {
    lines.push(`    else:`);
    lines.push(`        _match_result = ${exprToPython(expr.defaultArm, sourceVar)}`);
  }
  lines.push(`    # end match`);
  // Wrap in a lambda for inline use
  const inner = lines.join('\n');
  return `(lambda _match_val: (\n${inner}\n    )(_match_result))(${subject})`;

  // Simpler: just use dict lookup approach for all cases
  // Actually, let's keep the dict approach as primary since it's cleaner
}

function pipeToPython(expr: IRPipe, sourceVar: string): string {
  const left = exprToPython(expr.left, sourceVar);

  if (expr.right.kind === 'function_call') {
    const fnName = BUILTIN_FN_MAP[expr.right.name] ?? expr.right.name;
    const args = expr.right.args.map(a => exprToPython(a, sourceVar));
    return `${fnName}(${left}${args.length > 0 ? ', ' + args.join(', ') : ''})`;
  }

  // Fallback
  return `${exprToPython(expr.right, sourceVar)}(${left})`;
}

function binaryToPython(expr: IRBinary, sourceVar: string): string {
  const left = exprToPython(expr.left, sourceVar);
  const right = exprToPython(expr.right, sourceVar);
  return `${left} ${expr.operator} ${right}`;
}

function coalesceToPython(expr: IRCoalesce, sourceVar: string): string {
  // The ? operator: value is optional, propagate as-is
  return exprToPython(expr.expr, sourceVar);
}

function subMappingToPython(expr: IRSubMapping, sourceVar: string): string {
  return `${expr.mappingName}(${sourceVar})`;
}

function arrayLiteralToPython(expr: IRArrayLiteral, sourceVar: string): string {
  const elements = expr.elements.map((e: IRExpr) => exprToPython(e, sourceVar)).join(', ');
  return `[${elements}]`;
}

// ============================================================
// Type → Python string
// ============================================================
function irTypeToPython(t: IResolvedType): string {
  switch (t.kind) {
    case 'primitive':
      return primitiveToPython(t.name);
    case 'nominal':
      return t.name; // references type alias
    case 'optional':
      return `Optional[${irTypeToPython(t.inner)}]`;
    case 'array':
      return `list[${irTypeToPython(t.inner)}]`;
    case 'union':
      return t.variants.map(irTypeToPython).join(' | ');
    case 'refined':
      return irTypeToPython(t.base);
    case 'schema_ref':
      return `'${t.name}'`; // forward reference via string
    default: return 'Any'; // unreachable
  }
}

function primitiveToPython(name: string): string {
  switch (name) {
    case 'String': return 'str';
    case 'Int': return 'int';
    case 'Float': return 'float';
    case 'Decimal': return 'Decimal';
    case 'Bool': return 'bool';
    case 'DateTime': return 'datetime';
    case 'Uuid': return 'str';
    case 'Json': return 'dict';
    default: return 'Any';
  }
}

// ============================================================
// Built-in function name mapping (Lens → Python runtime)
// ============================================================
const BUILTIN_FN_MAP: Record<string, string> = {
  trim: '__trim',
  title_case: '__title_case',
  lowercase: '__lowercase',
  uppercase: '__uppercase',
  normalize_email: '__normalize_email',
  normalize_city: '__normalize_city',
  parse_uuid: '__parse_uuid',
  parse_int: '__parse_int',
  to_string: '__to_string',
  filter_none: '__filter_none',
  split_first: '__split_first',
  split_last: '__split_last',
  now: '__now',
};

// ============================================================
// Helpers
// ============================================================
function hasAnnotation(field: IRSchemaField, name: string): boolean {
  return field.annotations.some((a: IRAnnotation) => a.name === name);
}

function formatAnnotation(ann: IRAnnotation): string {
  if (ann.args.length === 0) return `@${ann.name}`;
  const args = ann.args.map((a: string | number | boolean) => {
    if (typeof a === 'string') return `"${a}"`;
    return String(a);
  }).join(', ');
  return `@${ann.name}(${args})`;
}

/** Simple topological sort: schemas referenced by others come first */
function topologicalSort(schemas: IRSchema[]): IRSchema[] {
  const refs = new Map<string, Set<string>>();
  for (const s of schemas) {
    refs.set(s.name, collectSchemaRefs(s));
  }

  const sorted: IRSchema[] = [];
  const visited = new Set<string>();
  const visiting = new Set<string>();

  function visit(name: string) {
    if (visited.has(name)) return;
    if (visiting.has(name)) {
      // Circular reference — break by skipping
      return;
    }
    visiting.add(name);
    const deps = refs.get(name) ?? new Set();
    for (const dep of deps) {
      if (schemas.some(s => s.name === dep)) {
        visit(dep);
      }
    }
    visiting.delete(name);
    visited.add(name);
    const schema = schemas.find(s => s.name === name);
    if (schema) sorted.push(schema);
  }

  for (const s of schemas) {
    visit(s.name);
  }

  return sorted;
}

function collectSchemaRefs(schema: IRSchema): Set<string> {
  const refs = new Set<string>();
  for (const f of schema.fields) {
    collectTypeRefs(f.type, refs);
  }
  return refs;
}

function collectTypeRefs(t: IResolvedType, refs: Set<string>): void {
  switch (t.kind) {
    case 'schema_ref':
      refs.add(t.name);
      break;
    case 'optional':
    case 'array':
      collectTypeRefs(t.inner, refs);
      break;
    case 'union':
      for (const v of t.variants) collectTypeRefs(v, refs);
      break;
    case 'refined':
      collectTypeRefs(t.base, refs);
      break;
  }
}
