// ============================================================
// TypeScript Code Generator — compiles Lens IR to TypeScript
// ============================================================

import {
  IRDocument, IRSchema, IRSchemaField, IRAnnotation,
  IRTypeAlias, IRMapping, IRMappingField, IRExpr,
  IRFieldAccess, IRLiteral, IRFunctionCall, IRMatch,
  IRMatchArm, IRPipe, IRBinary, IRCoalesce, IRSubMapping,
  IRArrayLiteral, IResolvedType,
} from '../ir';

export interface GenerateOptions {
  outputDir?: string;
  generateSchemas?: boolean;
  generateMappings?: boolean;
}

export function generateTypeScript(ir: IRDocument, options: GenerateOptions = {}): string {
  const opts = { generateSchemas: true, generateMappings: true, ...options };
  const lines: string[] = [];

  lines.push('// ============================================================');
  lines.push('// Generated by Lens DSL compiler — DO NOT EDIT');
  lines.push('// ============================================================');
  lines.push('');

  // Generate type aliases
  if (opts.generateSchemas) {
    for (const ta of ir.typeAliases) {
      lines.push(...generateTypeAlias(ta));
      lines.push('');
    }

    for (const schema of ir.schemas) {
      lines.push(...generateSchemaInterface(schema));
      lines.push('');
    }
  }

  // Generate mapping functions
  if (opts.generateMappings) {
    for (const mapping of ir.mappings) {
      if (mapping.isBidirectional) {
        lines.push(...generateBidirectionalMapping(mapping));
      } else {
        lines.push(...generateMappingFunction(mapping));
      }
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ---- Type Alias ----
function generateTypeAlias(ta: IRTypeAlias): string[] {
  const lines: string[] = [];
  lines.push(`// Type alias: ${ta.name}`);

  if (ta.defKind === 'regex') {
    lines.push(`// Refined type with pattern: ${ta.pattern}`);
    lines.push(`export type ${ta.name} = string; // refined: ${ta.pattern}`);
  } else if (ta.defKind === 'union') {
    const variants = (ta.variants ?? []).map((v: string) => `'${v}'`).join(' | ');
    lines.push(`export type ${ta.name} = ${variants};`);
  } else {
    const tsType = irTypeToTs(ta.resolvedType);
    lines.push(`export type ${ta.name} = ${tsType};`);
  }

  return lines;
}

// ---- Schema Interface ----
function generateSchemaInterface(schema: IRSchema): string[] {
  const lines: string[] = [];
  lines.push(`// Schema: ${schema.name}`);
  lines.push(`export interface ${schema.name} {`);

  for (const field of schema.fields) {
    const anns = field.annotations.map(formatAnnotation).filter(Boolean);
    if (anns.length > 0) {
      lines.push(`  /** ${anns.join(', ')} */`);
    }
    const tsType = irTypeToTs(field.type);
    lines.push(`  ${field.name}: ${tsType};`);
  }

  lines.push('}');
  return lines;
}

// ---- Type → TypeScript ----
function irTypeToTs(t: IResolvedType): string {
  switch (t.kind) {
    case 'primitive':
      return primitiveToTs(t.name);
    case 'nominal':
      return t.name;
    case 'optional':
      return `${irTypeToTs(t.inner)} | null`;
    case 'array':
      return `${irTypeToTs(t.inner)}[]`;
    case 'union':
      return t.variants.map((v: IResolvedType) => irTypeToTs(v)).join(' | ');
    case 'refined':
      return irTypeToTs(t.base);
    case 'schema_ref':
      return t.name;
  }
}

function primitiveToTs(name: string): string {
  switch (name) {
    case 'String': return 'string';
    case 'Int':
    case 'Float':
    case 'Decimal': return 'number';
    case 'Bool': return 'boolean';
    case 'DateTime': return 'Date';
    case 'Uuid': return 'string';
    case 'Json': return 'Record<string, unknown>';
    default: return 'unknown';
  }
}

function formatAnnotation(ann: IRAnnotation): string {
  if (ann.args.length === 0) return `@${ann.name}`;
  const args = ann.args.map((a: string | number | boolean) => {
    if (typeof a === 'string') return `"${a}"`;
    return String(a);
  }).join(', ');
  return `@${ann.name}(${args})`;
}

// ---- Mapping Function ----
function generateMappingFunction(mapping: IRMapping): string[] {
  const lines: string[] = [];
  lines.push(`// Mapping: ${mapping.name} (${mapping.source} -> ${mapping.target})`);
  lines.push(`export function ${mapping.name}(source: ${mapping.source}): ${mapping.target} {`);
  lines.push(`  return {`);
  for (const field of mapping.fields) {
    const valueExpr = exprToTs(field.expression, 'source');
    lines.push(`    ${field.name}: ${valueExpr},`);
  }
  lines.push(`  };`);
  lines.push(`}`);
  return lines;
}

// ---- Bidirectional Mapping ----
function generateBidirectionalMapping(mapping: IRMapping): string[] {
  const lines: string[] = [];
  const sourceType = mapping.source;
  const targetType = mapping.target;

  lines.push(`// Bidirectional Mapping: ${mapping.name} (${sourceType} <-> ${targetType})`);

  // Forward
  lines.push(`export function ${mapping.name}_forward(source: ${sourceType}): ${targetType} {`);
  lines.push(`  return {`);
  for (const field of mapping.fields) {
    lines.push(`    ${field.name}: ${exprToTs(field.expression, 'source')},`);
  }
  lines.push(`  };`);
  lines.push(`}`);

  // Backward
  lines.push(`export function ${mapping.name}_backward(source: ${targetType}): ${sourceType} {`);
  lines.push(`  return {`);
  for (const field of (mapping.backwardFields ?? [])) {
    lines.push(`    ${field.name}: ${exprToTs(field.expression, 'source')},`);
  }
  lines.push(`  };`);
  lines.push(`}`);

  return lines;
}

// ---- Expression → TypeScript ----
function exprToTs(expr: IRExpr, sourceVar: string): string {
  switch (expr.kind) {
    case 'field_access': return fieldAccessToTs(expr, sourceVar);
    case 'literal': return literalToTs(expr);
    case 'function_call': return functionCallToTs(expr, sourceVar);
    case 'match': return matchToTs(expr, sourceVar);
    case 'pipe': return pipeToTs(expr, sourceVar);
    case 'binary': return binaryToTs(expr, sourceVar);
    case 'coalesce': return coalesceToTs(expr, sourceVar);
    case 'sub_mapping': return subMappingToTs(expr, sourceVar);
    case 'array_literal': return arrayLiteralToTs(expr, sourceVar);
    default: return 'null';
  }
}

function fieldAccessToTs(expr: IRFieldAccess, sourceVar: string): string {
  const path = expr.path;
  if (path.length > 0 && path[0] === 'source') {
    const fieldPath = path.slice(1);
    if (fieldPath.length === 0) return sourceVar;
    return `${sourceVar}.${fieldPath.join('.')}`;
  }
  return JSON.stringify(path[0]);
}

function literalToTs(expr: IRLiteral): string {
  if (typeof expr.value === 'string') return JSON.stringify(expr.value);
  if (expr.value === null) return 'null';
  return String(expr.value);
}

function functionCallToTs(expr: IRFunctionCall, sourceVar: string): string {
  const fnName = BUILTIN_FN_MAP[expr.name] ?? expr.name;
  const args = expr.args.map((a: IRExpr) => exprToTs(a, sourceVar)).join(', ');
  if (args) return `${fnName}(${args})`;
  return `${fnName}()`;
}

function matchToTs(expr: IRMatch, sourceVar: string): string {
  const subject = exprToTs(expr.subject, sourceVar);
  const lines: string[] = [];

  const arms = expr.arms.map((arm: IRMatchArm) => ({
    patterns: arm.patterns.map((p: string | number | boolean) => JSON.stringify(p)),
    body: exprToTs(arm.body, sourceVar),
  }));

  const defaultBody = expr.defaultArm
    ? exprToTs(expr.defaultArm, sourceVar)
    : `(() => { throw new Error('Match error: no arm matched for ' + ${subject}); })()`;

  lines.push(`(() => {`);
  lines.push(`  switch (${subject}) {`);
  for (const arm of arms) {
    for (const p of arm.patterns) {
      lines.push(`    case ${p}:`);
    }
    lines.push(`      return ${arm.body};`);
  }
  lines.push(`    default:`);
  lines.push(`      return ${defaultBody};`);
  lines.push(`  }`);
  lines.push(`})()`);

  return lines.join('\n');
}

function pipeToTs(expr: IRPipe, sourceVar: string): string {
  const left = exprToTs(expr.left, sourceVar);
  if (expr.right.kind === 'function_call') {
    const fnName = BUILTIN_FN_MAP[expr.right.name] ?? expr.right.name;
    const args = expr.right.args.map((a: IRExpr) => exprToTs(a, sourceVar));
    return `${fnName}(${left}${args.length > 0 ? ', ' + args.join(', ') : ''})`;
  }
  return `${exprToTs(expr.right, sourceVar)}(${left})`;
}

function binaryToTs(expr: IRBinary, sourceVar: string): string {
  const left = exprToTs(expr.left, sourceVar);
  const right = exprToTs(expr.right, sourceVar);
  return `${left} ${expr.operator} ${right}`;
}

function coalesceToTs(expr: IRCoalesce, sourceVar: string): string {
  return exprToTs(expr.expr, sourceVar);
}

function subMappingToTs(expr: IRSubMapping, sourceVar: string): string {
  return `${expr.mappingName}(${sourceVar})`;
}

function arrayLiteralToTs(expr: IRArrayLiteral, sourceVar: string): string {
  const elements = expr.elements.map((e: IRExpr) => exprToTs(e, sourceVar)).join(', ');
  return `[${elements}]`;
}

// ---- Built-in Function Name Mapping (Lens → TypeScript runtime) ----
const BUILTIN_FN_MAP: Record<string, string> = {
  trim: '__trim',
  title_case: '__titleCase',
  lowercase: '__lowercase',
  uppercase: '__uppercase',
  normalize_email: '__normalizeEmail',
  normalize_city: '__normalizeCity',
  parse_uuid: '__parseUuid',
  parse_int: '__parseInt',
  to_string: '__toString',
  filter_none: '__filterNone',
  split_first: '__splitFirst',
  split_last: '__splitLast',
  now: '__now',
};
