// ============================================================
// TypeScript Code Generator — compiles Lens AST to TypeScript
// ============================================================

import {
  Document, SchemaDecl, TypeAliasDecl, MappingDecl,
  BidirectionalMappingDecl, MappingBlock, MappingField, MappingExpr,
  FieldAccessExpr, LiteralExpr, FunctionCallExpr, MatchExpr,
  PipeExpr, BinaryExpr, CoalesceExpr, SubMappingExpr,
  ArrayLiteralExpr, Annotation, TypeAliasDef, TypeExpr,
} from '../parser/ast';

export interface GenerateOptions {
  outputDir?: string;
  generateSchemas?: boolean;
  generateMappings?: boolean;
}

export function generateTypeScript(document: Document, options: GenerateOptions = {}): string {
  const opts = { generateSchemas: true, generateMappings: true, ...options };
  const lines: string[] = [];

  lines.push('// ============================================================');
  lines.push('// Generated by Lens DSL compiler — DO NOT EDIT');
  lines.push('// ============================================================');
  lines.push('');

  // Separate declarations
  const schemas: SchemaDecl[] = [];
  const typeAliases: TypeAliasDecl[] = [];
  const mappings: MappingDecl[] = [];
  const bidirMappings: BidirectionalMappingDecl[] = [];

  for (const decl of document.declarations) {
    switch (decl.kind) {
      case 'schema_decl': schemas.push(decl); break;
      case 'type_alias_decl': typeAliases.push(decl); break;
      case 'mapping_decl': mappings.push(decl); break;
      case 'bidirectional_mapping_decl': bidirMappings.push(decl); break;
    }
  }

  // Generate type aliases (as TypeScript types)
  if (opts.generateSchemas) {
    for (const ta of typeAliases) {
      lines.push(...generateTypeAlias(ta));
      lines.push('');
    }

    // Generate schema interfaces
    for (const schema of schemas) {
      lines.push(...generateSchemaInterface(schema));
      lines.push('');
    }
  }

  // Generate mapping functions
  if (opts.generateMappings) {
    for (const mapping of mappings) {
      lines.push(...generateMappingFunction(mapping));
      lines.push('');
    }

    for (const bidir of bidirMappings) {
      lines.push(...generateBidirectionalMapping(bidir));
      lines.push('');
    }
  }

  return lines.join('\n');
}

// ---- Type Alias Codegen ----
function generateTypeAlias(ta: TypeAliasDecl): string[] {
  const lines: string[] = [];
  lines.push(`// Type alias: ${ta.name}`);

  if (ta.definition.kind === 'alias_regex') {
    lines.push(`// Refined type with pattern: ${ta.definition.pattern}`);
    lines.push(`export type ${ta.name} = string; // refined: ${ta.definition.pattern}`);
  } else if (ta.definition.kind === 'alias_union') {
    const variants = ta.definition.variants.map(v => `'${v}'`).join(' | ');
    lines.push(`export type ${ta.name} = ${variants};`);
  } else if (ta.definition.kind === 'alias_wrapper') {
    const tsType = typeExprToTs(ta.definition.inner);
    lines.push(`export type ${ta.name} = ${tsType};`);
  }

  return lines;
}

// ---- Schema Interface Codegen ----
function generateSchemaInterface(schema: SchemaDecl): string[] {
  const lines: string[] = [];
  lines.push(`// Schema: ${schema.name}`);
  lines.push(`export interface ${schema.name} {`);

  for (const field of schema.fields) {
    const anns = field.annotations.map(a => formatAnnotation(a)).filter(Boolean);
    if (anns.length > 0) {
      lines.push(`  /** ${anns.join(', ')} */`);
    }
    const tsType = typeExprToTs(field.type);
    lines.push(`  ${field.name}: ${tsType};`);
  }

  lines.push('}');
  return lines;
}

// ---- Type Expression → TypeScript ----
function typeExprToTs(type: TypeExpr): string {
  switch (type.kind) {
    case 'primitive':
      return primitiveToTs(type.name);
    case 'nominal':
      return type.name;
    case 'optional':
      return `${typeExprToTs(type.inner)} | null`;
    case 'array':
      return `${typeExprToTs(type.inner)}[]`;
    case 'union':
      return type.variants.map(v => typeExprToTs(v)).join(' | ');
    case 'refined':
      return typeExprToTs(type.base);
    case 'schema_ref':
      return type.name;
  }
}

function primitiveToTs(name: string): string {
  switch (name) {
    case 'String': return 'string';
    case 'Int':
    case 'Float':
    case 'Decimal': return 'number';
    case 'Bool': return 'boolean';
    case 'DateTime': return 'Date';
    case 'Uuid': return 'string';
    case 'Json': return 'Record<string, unknown>';
    default: return 'unknown';
  }
}

function formatAnnotation(a: Annotation): string {
  if (a.args.length === 0) return `@${a.name}`;
  const args = a.args.map(arg => {
    switch (arg.kind) {
      case 'arg_string': return `"${arg.value}"`;
      case 'arg_number': return String(arg.value);
      case 'arg_boolean': return String(arg.value);
      case 'arg_identifier': return arg.value;
      case 'arg_regex': return `/${arg.value}/`;
    }
  }).join(', ');
  return `@${a.name}(${args})`;
}

// ---- Mapping Function Codegen ----
function generateMappingFunction(mapping: MappingDecl): string[] {
  const lines: string[] = [];
  const sourceType = mapping.source;
  const targetType = mapping.target;

  lines.push(`// Mapping: ${mapping.name} (${sourceType} -> ${targetType})`);
  lines.push(`export function ${mapping.name}(source: ${sourceType}): ${targetType} {`);
  lines.push(`  return {`);

  for (const field of mapping.fields) {
    const valueExpr = mappingExprToTs(field.expression, 'source');
    lines.push(`    ${field.name}: ${valueExpr},`);
  }

  lines.push(`  };`);
  lines.push(`}`);

  return lines;
}

// ---- Bidirectional Mapping Codegen ----
function generateBidirectionalMapping(mapping: BidirectionalMappingDecl): string[] {
  const lines: string[] = [];
  const sourceType = mapping.source;
  const targetType = mapping.target;

  lines.push(`// Bidirectional Mapping: ${mapping.name} (${sourceType} <-> ${targetType})`);

  // Forward
  lines.push(`export function ${mapping.name}_forward(source: ${sourceType}): ${targetType} {`);
  lines.push(`  return {`);
  for (const field of mapping.forward.fields) {
    lines.push(`    ${field.name}: ${mappingExprToTs(field.expression, 'source')},`);
  }
  lines.push(`  };`);
  lines.push(`}`);

  // Backward
  lines.push(`export function ${mapping.name}_backward(source: ${targetType}): ${sourceType} {`);
  lines.push(`  return {`);
  for (const field of mapping.backward.fields) {
    lines.push(`    ${field.name}: ${mappingExprToTs(field.expression, 'source')},`);
  }
  lines.push(`  };`);
  lines.push(`}`);

  return lines;
}

// ---- Mapping Expression → TypeScript ----
function mappingExprToTs(expr: MappingExpr, sourceVar: string): string {
  switch (expr.kind) {
    case 'field_access':
      return fieldAccessToTs(expr, sourceVar);
    case 'literal':
      return literalToTs(expr);
    case 'function_call':
      return functionCallToTs(expr, sourceVar);
    case 'match':
      return matchToTs(expr, sourceVar);
    case 'pipe':
      return pipeToTs(expr, sourceVar);
    case 'binary':
      return binaryToTs(expr, sourceVar);
    case 'coalesce':
      return coalesceToTs(expr, sourceVar);
    case 'sub_mapping':
      return subMappingToTs(expr, sourceVar);
    case 'array_literal':
      return arrayLiteralToTs(expr, sourceVar);
  }
}

function fieldAccessToTs(expr: FieldAccessExpr, sourceVar: string): string {
  const path = expr.path;
  
  // If path starts with 'source', emit sourceVar.field...
  if (path.length > 0 && path[0] === 'source') {
    const fieldPath = path.slice(1);
    if (fieldPath.length === 0) return sourceVar;
    return `${sourceVar}.${fieldPath.join('.')}`;
  }
  
  // Standalone identifier — likely a variant literal
  return JSON.stringify(path[0]);
}

function literalToTs(expr: LiteralExpr): string {
  if (typeof expr.value === 'string') return JSON.stringify(expr.value);
  if (expr.value === null) return 'null';
  return String(expr.value);
}

function functionCallToTs(expr: FunctionCallExpr, sourceVar: string): string {
  const fnName = BUILTIN_FN_MAP[expr.name] ?? expr.name;
  const args = expr.args.map(a => mappingExprToTs(a, sourceVar)).join(', ');
  if (args) {
    return `${fnName}(${args})`;
  }
  return `${fnName}()`;
}

function matchToTs(expr: MatchExpr, sourceVar: string): string {
  const subject = mappingExprToTs(expr.subject, sourceVar);
  const lines: string[] = [];
  
  // Check if we're matching against enum-like union values
  // Generate a switch or ternary chain
  const arms = expr.arms.map(arm => {
    const patterns = arm.pattern.kind === 'multi_pattern'
      ? arm.pattern.values.map(v => JSON.stringify(v))
      : arm.pattern.kind === 'literal_pattern'
        ? [JSON.stringify(arm.pattern.value)]
        : [];
    const body = mappingExprToTs(arm.body, sourceVar);
    return { patterns, body };
  });

  const defaultBody = expr.defaultArm
    ? mappingExprToTs(expr.defaultArm, sourceVar)
    : `(() => { throw new Error('Match error: no arm matched for ' + ${subject}); })()`;

  // Use a switch for clarity
  lines.push(`(() => {`);
  lines.push(`  switch (${subject}) {`);
  for (const arm of arms) {
    for (const p of arm.patterns) {
      lines.push(`    case ${p}:`);
    }
    lines.push(`      return ${arm.body};`);
  }
  lines.push(`    default:`);
  lines.push(`      return ${defaultBody};`);
  lines.push(`  }`);
  lines.push(`})()`);

  return lines.join('\n');
}

function pipeToTs(expr: PipeExpr, sourceVar: string): string {
  const left = mappingExprToTs(expr.left, sourceVar);
  if (expr.right.kind === 'function_call') {
    const fnName = BUILTIN_FN_MAP[expr.right.name] ?? expr.right.name;
    const args = expr.right.args.map(a => mappingExprToTs(a, sourceVar));
    return `${fnName}(${left}${args.length > 0 ? ', ' + args.join(', ') : ''})`;
  }
  // Fallback
  return `${mappingExprToTs(expr.right, sourceVar)}(${left})`;
}

function binaryToTs(expr: BinaryExpr, sourceVar: string): string {
  const left = mappingExprToTs(expr.left, sourceVar);
  const right = mappingExprToTs(expr.right, sourceVar);
  return `${left} ${expr.operator} ${right}`;
}

function coalesceToTs(expr: CoalesceExpr, sourceVar: string): string {
  // The ? operator means: if this value is null/undefined, it's fine
  // In TypeScript, accessing optional chain
  const inner = mappingExprToTs(expr.expr, sourceVar);
  return inner; // For MVP, just pass through — the type system handles null
}

function subMappingToTs(expr: SubMappingExpr, sourceVar: string): string {
  // map source via MappingName
  return `${expr.mappingName}(${sourceVar})`;
}

function arrayLiteralToTs(expr: ArrayLiteralExpr, sourceVar: string): string {
  const elements = expr.elements.map(e => mappingExprToTs(e, sourceVar)).join(', ');
  return `[${elements}]`;
}

// ---- Built-in Function Name Mapping (Lens → TypeScript runtime) ----
const BUILTIN_FN_MAP: Record<string, string> = {
  trim: '__trim',
  title_case: '__titleCase',
  lowercase: '__lowercase',
  uppercase: '__uppercase',
  normalize_email: '__normalizeEmail',
  normalize_city: '__normalizeCity',
  parse_uuid: '__parseUuid',
  parse_int: '__parseInt',
  to_string: '__toString',
  filter_none: '__filterNone',
  split_first: '__splitFirst',
  split_last: '__splitLast',
  now: '__now',
};
